Models/Pet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pet()
        {
            this.AddtoCarts = new HashSet<AddtoCart>();
            this.Buys = new HashSet<Buy>();
        }
        [Key]
    
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Species { get; set; }
        [Required]
        public string Breed { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        [Required]
        public Nullable<bool> IsAvailable { get; set; }
        [Required]
        public Nullable<int> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddtoCart> AddtoCarts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buy> Buys { get; set; }
    }
}

Models/User.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


Controllers/AddtoCartsController.cs
using System;

using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.Linq;

using System.Web;

using System.Web.Mvc; 

using Shop.Models;


namespace Shop.Controllers
{

    //[Authorize]
    public class AddtoCartsController : Controller

    {

        WebsiteEntities db = new WebsiteEntities();

        // GET: MyCart


        public ActionResult CartView()

        {
            

            List<AddtoCart> cart = Session["Cart"] as List<AddtoCart>;

            if (cart == null)

            {

                cart = new List<AddtoCart>();

                Session["Cart"] = cart;

            }

            return View(cart);

        }

        public ActionResult PaidView()
        {
            return View();
        }




        // GET: Products/AddToCart

        [HttpPost]

        public ActionResult AddToCart(int id, string name, int price, int quantity = 1)

        {

            List<AddtoCart> cart = Session["Cart"] as List<AddtoCart> ?? new List<AddtoCart>();

            AddtoCart existingItem = cart.FirstOrDefault(item => item.Id == id);

            if (existingItem != null)

            {

                existingItem.Quantity += quantity;

            }

            else

            {

                cart.Add(new AddtoCart { Id = id, Price = price, Name = name, Quantity = quantity });

            }

            Session["Cart"] = cart;

            return RedirectToAction("CartView");

        }

        public ActionResult RemoveFromCart(int id)

        {

            List<AddtoCart> cart = Session["Cart"] as List<AddtoCart>;

            if (cart != null)

            {

                cart.RemoveAll(item => item.Id == id);

                Session["Cart"] = cart;

            }

            return RedirectToAction("CartView");
        }

        public int GetCurrentUserId()
        {
            return 1;
        }
        
        public ActionResult Checkout()

        {

            // Retrieve cart items from session

            List<AddtoCart> cartItems = Session["Cart"] as List<AddtoCart>;

            if (cartItems == null || cartItems.Count == 0)

            {

                // Redirect to an empty cart page or display a message

                return RedirectToAction("EmptyCart");

            }

            // Calculate total amount

            int price = (int)cartItems.Sum(item => item.Price * item.Quantity);

            // Create a new order

            var buy = new Buy

            {

                Id = GetCurrentUserId(), // Replace with actual logic to get the current user ID

                Price = price,

                BuyDate = DateTime.Now,


                 // Set the initial order status

            };

            // Save the order to the database

            db.Buys.Add(buy);

            db.SaveChanges();

            // Optionally, you can clear the cart session after creating the order

            Session["Cart"] = null;

            // Redirect to the order confirmation page with the order ID

            return RedirectToAction("PaidView", new { orderId = buy.Id }); 

        }
        public ActionResult ClearCart()

        {


            Session.Remove("Cart");

            return Redirect("~/Pets/UserView");

        }
    }

}

Controllers/BuyController.cs
using Shop.Models;
using Shop.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Web;
using System.Web.Mvc;

namespace RegistrationLogin.Controllers
{
    public class BuyController : Controller
    {
        private WebsiteEntities db = new WebsiteEntities();
        // GET: Order
        public ActionResult Index()
        {
            return View();
        }

        // Action to display order history for the current user
        public ActionResult OrdersList()
        {
            
            return View(db.Buys.ToList());
        }
    }
}

Controllers/PetsController.cs

using System;

using System.Collections.Generic;

using System.Data;

using System.Data.Entity;
using System.Linq;

using System.Net;

using System.Web;

using System.Web.Mvc;

using Shop.Models;
 
namespace Shop.Controllers

{

    public class PetsController : Controller

    {

        private WebsiteEntities db = new WebsiteEntities();

        // GET: tb_pet

        public ActionResult Index()

        {
            
            if (Session["IsLoggedIn"] == null || (bool)Session["IsLoggedIn"] == false)

            {

                return HttpNotFound();

            }

            return View(db.Pets.ToList());


        }

        public ActionResult UserView()

        {
            

            if (Session["IsLoggedIn"] == null || (bool)Session["IsLoggedIn"] == false)

            {

                return HttpNotFound();

            }

            return View(db.Pets.ToList());


        }

        // GET: tb_pet/Details/5

        public ActionResult Details(int? id)

        {

            if (id == null)

            {

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }

            Pet Pets = db.Pets.Find(id);

            if (Pets == null)

            {

                return HttpNotFound();

            }

            return View(Pets);

        }

        // GET: tb_pet/Create

        public ActionResult Create()

        {

            return View();

        }

        // POST: tb_pet/Create

        // To protect from overposting attacks, enable the specific properties you want to bind to, for 

        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]

        [ValidateAntiForgeryToken]

        public ActionResult Create([Bind(Include = "id,Name,species,breed,dateofbirth,IsAvailable,Price")] Pet Pet)

        {

            if (ModelState.IsValid)

            {

                db.Pets.Add(Pet);

                db.SaveChanges();

                return RedirectToAction("Index");

            }

            return View(Pet);

        }

        // GET: tb_pet/Edit/5

        public ActionResult Edit(int? id)

        {

            if (id == null)

            {

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }

            Pet Pet = db.Pets.Find(id);

            if (Pet == null)

            {

                return HttpNotFound();

            }

            return View(Pet);

        }

        // POST: tb_pet/Edit/5

        // To protect from overposting attacks, enable the specific properties you want to bind to, for 

        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]

        [ValidateAntiForgeryToken]

        public ActionResult Edit([Bind(Include = "id,Name,species,breed,dateofbirth,IsAvailable,Price")] Pet Pet)

        {

            if (ModelState.IsValid)

            {

                db.Entry(Pet).State = EntityState.Modified;

                db.SaveChanges();

                return RedirectToAction("Index");

            }

            return View(Pet);

        }

        // GET: tb_pet/Delete/5

        public ActionResult Delete(int? id)

        {

            if (id == null)

            {

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }

            Pet Pet = db.Pets.Find(id);

            if (Pet == null)

            {

                return HttpNotFound();

            }

            return View(Pet);

        }

        // POST: tb_pet/Delete/5

        [HttpPost, ActionName("Delete")]

        [ValidateAntiForgeryToken]

        public ActionResult DeleteConfirmed(int id)

        {

            Pet Pet = db.Pets.Find(id);

            db.Pets.Remove(Pet);

            db.SaveChanges();

            return RedirectToAction("Index");

        }

        protected override void Dispose(bool disposing)

        {

            if (disposing)

            {

                db.Dispose();

            }

            base.Dispose(disposing);

        }

    }

}

Views/Pets/Create.cshtml
@model Shop.Models.Pet

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_newLayout.cshtml";
}

<h2>Create</h2>
@using (Html.BeginForm("Create", "Pets", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Pet</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Species, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Species, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Species, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Breed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Breed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Breed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsAvailable)
                    @Html.ValidationMessageFor(model => model.IsAvailable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Pets/Delete.cshtml
@model Shop.Models.Pet

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_newLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Species)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Species)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Breed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Breed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

       

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Pets/Details.cshtml
@model Shop.Models.Pet

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_newLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Pet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Species)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Species)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Breed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Breed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Pets/Edit.cshtml
@model Shop.Models.Pet

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_newLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Pet</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Species, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Species, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Species, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Breed, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Breed, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Breed, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IsAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsAvailable)
                @Html.ValidationMessageFor(model => model.IsAvailable, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Pets/Index.cshtml
@model IEnumerable<Shop.Models.Pet>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_newLayout.cshtml";
}

<h2>Index</h2>

@Html.ActionLink("Order list", "OrdersList","Buy")

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Species)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Breed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Species)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Breed)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfBirth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsAvailable)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>


<style>
    html {
        font-size: 20px;
    }
    body {
        background-image: url('../Images/pink.png');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100% 100%;
    }
</style>

Views/Pets/UserView.cshtml
@model IEnumerable<Shop.Models.Pet>

@{
    ViewBag.Title = "UserView";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<h2>UserView</h2>

<style>
    /* Basic styling */
    html {
        font-size: 20px;
    }
    body {
        font-family: Arial, sans-serif;
        background-image: url('../Images/lightblue1.jpg');
        background-color: #f9f9f9;
        padding: 20px;
    }

    .pet {
        border: 1px solid #ddd;
        padding: 10px;
        margin: 10px;
        background-color: #fff;
        border:solid;
        border-block-color: black;
        border-color: black;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .popup {
        display: none;
        position: fixed;
        top: 50%;
        left: 50%;
        background-color: orange;
        padding: 20px;
    }
    

    .pet img {
        max-width: 100%;
        height: auto;
    }

    .pet h3 {
        margin: 10px 0;
    }

    .pet p {
        color: #555;
    }
    .button {
        transition-duration: 0.4s;
    }

        .button:hover {
            background-color: #04AA6D; /* Green */
            color: white;
        }
</style>
</head>
<body>

    <body>
        @Html.ActionLink("View your cart","CartView","AddtoCarts")

        @foreach (var item in Model)
        {
             <div class="pet">

                 <h3>@item.Name</h3>
                 <p>@item.Name<br>Species: @item.Species<br>Breed: @item.Breed<br>Date Of Birth: @item.DateOfBirth<br>Is Available: @item.IsAvailable<br>Price: @item.Price</p>

                 @using (Html.BeginForm("AddToCart", "AddtoCarts", new { Id = item.Id, Name = item.Name, price = item.Price }, FormMethod.Post))

                 {

                     <input type="hidden" name="Id" value="@item.Id" />

                     <input type="number" name="quantity" value="1" min="1" />

                     <input type="submit" value="Add to Cart" class="btn btn-primary" />


                 }
                 <br />




             </div>
         }

        <script>
            const addToCartBtn = document.getElementById('add-to-cart-btn');
            const popup = document.getElementById('popup');

            addToCartBtn.addEventListener('click', function () {
                popup.style.display = 'block';

                setTimeout(function () {
                    popup.style.display = 'none';
                }, 3000);
            });
            

        </script>
    </body>

